  AWSTemplateFormatVersion: '2010-09-09'
  Transform: AWS::Serverless-2016-10-31
  Description: AI ChatBot - WebSocket + Bedrock + ServiceNow + Genesys

  #############################################################
  # Run sam deploy and then run 
  # aws s3 cp Bedrock/bob-training.jsonl s3://bob-training-data-<acct>-<region>/
  # to upload the training data for Bob customization
  #
  # After the stack is deployed, run the following
  # outputs as cli commands to start the Bedrock model customization job:
  # UploadTrainingDataCommand
  # StartModelTrainingCommand (only once fine tuning is enabled in eu-west-2)
  # Then run the following to load the AI guardrailsw
  # aws bedrock create-guardrail --cli-input-json file://Bedrock/computer-guardrail.json
  # then
  # aws bedrock publish-guardrail --guardrail-identifier ekricr3x6tsa --version 1


  #############################################################

  Globals:
    Function:
      Runtime: python3.11
      Timeout: 15
      MemorySize: 256

  Parameters:

    AIModel:
      Type: String
      Default: mistral.mistral-7b-instruct-v0:2
  
    ConnectionsTableName:
      Type: String
      Default: WS_Chat_Connections

    BedrockModelId:
      Type: String
      Default: "mistral.mistral-7b-instruct-v0:2"

    ServiceNowBaseUrl:
      Type: String
      Default: https://your-instance.service-now.com

    GenesysBaseUrl:
      Type: String
      Default: https://api.mypurecloud.com

  Resources:

    ###########################################################
    # DynamoDB Tables
    ###########################################################

    # This table stores the WebSocket connection IDs for active clients
    ConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: !Ref ConnectionsTableName
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH

    # This table maps Genesys conversation IDs to WebSocket connection IDs
    # so it can route messages back to the correct customer

    GenesysConversationMap:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: GenesysConversationMap
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: genesysConversationId
            AttributeType: S
        KeySchema:
          - AttributeName: genesysConversationId
            KeyType: HASH
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
        SSESpecification:
          SSEEnabled: true

    # stores the chat history for a connection to persist the model state
    # for the AI
    ChatHistory:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ChatHistory
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: N
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        SSESpecification:
          SSEEnabled: true

    ###########################################################
    # WebSocket API
    ###########################################################
    WebSocketApi:
      Type: AWS::ApiGatewayV2::Api
      Properties:
        Name: AIChatBotWebSocket
        ProtocolType: WEBSOCKET
        RouteSelectionExpression: "$request.body.action"

    ###########################################################
    # WebSocket Stage (must depend on LogGroup)
    ###########################################################
    
    WebSocketStage:
      Type: AWS::ApiGatewayV2::Stage
      Properties:
        ApiId: !Ref WebSocketApi
        StageName: prod
        AutoDeploy: true
        DefaultRouteSettings:
          LoggingLevel: INFO
          DataTraceEnabled: true


    ###########################################################
    # WebSocket Routes
    ###########################################################
    ConnectRoute:
      Type: AWS::ApiGatewayV2::Route
      Properties:
        ApiId: !Ref WebSocketApi
        RouteKey: "$connect"
        AuthorizationType: CUSTOM
        AuthorizerId: !Ref WebSocketAuthorizerConfig
        Target: !Sub "integrations/${ConnectIntegration}"

    DisconnectRoute:
      Type: AWS::ApiGatewayV2::Route
      Properties:
        ApiId: !Ref WebSocketApi
        RouteKey: "$disconnect"
        Target: !Sub "integrations/${DisconnectIntegration}"
        
    ChatProcessorRoute:
      Type: AWS::ApiGatewayV2::Route
      Properties:
        ApiId: !Ref WebSocketApi
        RouteKey: "sendMessage"
        Target: !Sub "integrations/${ChatProcessorIntegration}"

    ###########################################################
    # WebSocket Integrations
    ###########################################################
    ConnectIntegration:
      Type: AWS::ApiGatewayV2::Integration
      Properties:
        ApiId: !Ref WebSocketApi
        IntegrationType: AWS_PROXY
        IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ConnectionHandler.Arn}/invocations
        CredentialsArn: !GetAtt WebSocketIntegrationInvokeRole.Arn
        PayloadFormatVersion: "1.0"

    DisconnectIntegration:
      Type: AWS::ApiGatewayV2::Integration
      Properties:
        ApiId: !Ref WebSocketApi
        IntegrationType: AWS_PROXY
        IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ConnectionHandler.Arn}/invocations
        CredentialsArn: !GetAtt WebSocketIntegrationInvokeRole.Arn
        PayloadFormatVersion: "1.0"
        
    ChatProcessorIntegration:
      Type: AWS::ApiGatewayV2::Integration
      Properties:
        ApiId: !Ref WebSocketApi
        IntegrationType: AWS_PROXY
        IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ChatProcessor.Arn}/invocations
        CredentialsArn: !GetAtt WebSocketIntegrationInvokeRole.Arn
        PayloadFormatVersion: "1.0"

    ###########################################################
    # Lambda: Connection Handler
    ###########################################################
    ConnectionHandler:
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: backend/src/
        Handler: app.lambda_handler
        Environment:
          Variables:
            CONNECTIONS_TABLE_NAME: !Ref ConnectionsTableName
        Policies:
          - DynamoDBCrudPolicy:
              TableName: !Ref ConnectionsTableName
          - AWSLambdaBasicExecutionRole
          - Statement:
              Effect: Allow
              Action:
                - execute-api:ManageConnections
              Resource: "arn:aws:execute-api:*:*:*/@connections/*"

    ConnectionHandlerInvokePermissionConnect:
      Type: AWS::Lambda::Permission
      Properties:
        Action: lambda:InvokeFunction
        FunctionName: !Ref ConnectionHandler
        Principal: apigateway.amazonaws.com
        SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketApi}/*/$connect

    ConnectionHandlerInvokePermissionDisconnect:
      Type: AWS::Lambda::Permission
      Properties:
        Action: lambda:InvokeFunction
        FunctionName: !Ref ConnectionHandler
        Principal: apigateway.amazonaws.com
        SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketApi}/*/$disconnect

  #############################################################
  # Lambda Chat Processor (handles messages from clients)
  #############################################################

    ChatProcessor:
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: backend/src/
        Handler: chat_processor.app.lambda_handler
        Environment:
          Variables:
            CONNECTIONS_TABLE_NAME: !Ref ConnectionsTableName
            AI_MODEL: !Ref AIModel
        Policies:
          - DynamoDBCrudPolicy:
              TableName: !Ref ConnectionsTableName
          - AWSLambdaBasicExecutionRole
          - Statement:
              Effect: Allow
              Action:
                - execute-api:ManageConnections
              Resource: "arn:aws:execute-api:*:*:*/@connections/*"
          - Statement:
              Effect: Allow
              Action:
                - bedrock:InvokeModel
                - bedrock:InvokeModelWithResponseStream
              Resource: !Sub "arn:aws:bedrock:eu-west-2::foundation-model/${AIModel}"
          - Statement: 
              Effect: Allow
              Action: 
                  - bedrock:CreateGuardrail
                  - bedrock:UpdateGuardrail
                  - bedrock:GetGuardrail
                  - bedrock:ListGuardrails
                  - bedrock:CreateGuardrailVersion
                  - bedrock:ApplyGuardrail
              
              Resource: "*" 
          - Statement:
            - Sid: S3ListBucketPermissions
              Effect: Allow
              Action:
                - s3:ListBucket
              Resource:
                - !Sub "${BobTrainingBucket.Arn}"
          - Statement:
            - Sid: S3Permissions
              Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
              Resource:
                - !Sub "${BobTrainingBucket.Arn}/*"
          - Statement:
            - Sid: DynamoDBPermissions
              Effect: Allow
              Action:
                - dynamodb:Query
                - dynamodb:PutItem
                - dynamodb:GetItem
              Resource:
                 - !GetAtt ChatHistory.Arn
              

    ChatProcessorInvokePermission:
      Type: AWS::Lambda::Permission
      Properties:
        Action: lambda:InvokeFunction
        FunctionName: !Ref ChatProcessor
        Principal: apigateway.amazonaws.com
        SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketApi}/*/*

  ############################################################
  # Websocket Authorizer
  ############################################################

    WebSocketAuthorizer:
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: backend/src/authoriser/
        Handler: app.lambda_handler
        Runtime: python3.11
        Policies:
          - AWSLambdaBasicExecutionRole
          
    WebSocketIntegrationInvokeRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: apigateway.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: AllowInvokeConnectLambda
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action: lambda:InvokeFunction
                  Resource: 
                    - !GetAtt ConnectionHandler.Arn
                    - !Sub "${ConnectionHandler.Arn}:*"
                    - !GetAtt ChatProcessor.Arn
                    - !Sub "${ChatProcessor.Arn}:*"
    
    WebSocketAuthorizerConfig:
      Type: AWS::ApiGatewayV2::Authorizer    
      Properties:
        ApiId: !Ref WebSocketApi
        AuthorizerType: REQUEST
        Name: WebSocketOAuthAuthorizer
        IdentitySource:
          - route.request.querystring.token
        AuthorizerUri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations
          - { LambdaArn: !GetAtt WebSocketAuthorizer.Arn }
        AuthorizerCredentialsArn: !GetAtt WebSocketAuthorizerInvokeRole.Arn

    WebSocketAuthorizerInvokeRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: apigateway.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: AllowInvokeAuthorizerLambda
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action: lambda:InvokeFunction
                  Resource: !GetAtt WebSocketAuthorizer.Arn

    WebSocketAuthorizerInvokePermission:
      Type: AWS::Lambda::Permission
      Properties:
        Action: lambda:InvokeFunction
        FunctionName: !Ref WebSocketAuthorizer
        Principal: apigateway.amazonaws.com
        SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketApi}/authorizers/*

    WebSocketSecret:
      Type: AWS::SecretsManager::Secret
      DeletionPolicy: Delete
      UpdateReplacePolicy: Delete
      Properties:
        Name: ai-chatbot-websocket-secret
        Description: Secret used for WebSocket authorizer demo
        SecretString: "abc123"

  ############################################################
  # Bedrock Elements
  ############################################################

    BobTrainingBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Sub "bob-training-data-${AWS::AccountId}-${AWS::Region}"
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true      
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
    
    BedrockCustomizationRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: BedrockCustomizationRole
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - bedrock.amazonaws.com
              Action:
                - sts:AssumeRole
        Policies:
          - PolicyName: BedrockCustomizationAccess
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                # Allow Bedrock to read your training data
                - Effect: Allow
                  Action:
                    - s3:GetObject
                    - s3:ListBucket
                  Resource:
                    - !Sub "${BobTrainingBucket.Arn}"
                    - !Sub "${BobTrainingBucket.Arn}/*"

                # Allow Bedrock to write model artifacts
                - Effect: Allow
                  Action:
                    - s3:PutObject
                  Resource:
                    - !Sub "${BobTrainingBucket.Arn}/*"

                # Allow Bedrock to create and manage customization jobs
                - Effect: Allow
                  Action:
                    - bedrock:CreateModelCustomizationJob
                    - bedrock:GetModelCustomizationJob
                    - bedrock:ListModelCustomizationJobs
                  Resource: "*"
#####################################################
# SQS Queues
#####################################################
    InboundMessagesQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: InboundMessages
        VisibilityTimeout: 30
        MessageRetentionPeriod: 345600   # 4 days
        ReceiveMessageWaitTimeSeconds: 20

    OutboundMessagesQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: OutboundMessages
        VisibilityTimeout: 30
        MessageRetentionPeriod: 345600   # 4 days
        ReceiveMessageWaitTimeSeconds: 20
             
  ############################################################
  # Roles
  #############################################################

    ApiGatewayCloudWatchRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ApiGatewayCloudWatchRole
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: apigateway.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs

    ApiGatewayAccount:
      Type: AWS::ApiGateway::Account
      Properties:
        CloudWatchRoleArn: !GetAtt ApiGatewayCloudWatchRole.Arn

    WebSocketApiExecutionRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service: apigateway.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: WebSocketApiExecutionPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - lambda:InvokeFunction
                  Resource: "*"

  Outputs:
    WebSocketEndpoint:
      Description: WebSocket URL for the chat frontend
      Value: !Sub "wss://${WebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/prod"

    BobsTrainingBucketName:
      Description: S3 Bucket for Bob training data
      Value: !Ref BobTrainingBucket

    BedrockCustomizationRole:
      Description: IAM Role for Bedrock customization
      Value: !GetAtt BedrockCustomizationRole.Arn
    
    UploadTrainingDataCommand:
      Description: PowerShell command to upload the training JSONL file
      Value: !Sub "aws s3 cp Bedrock/bob-training.jsonl s3://${BobTrainingBucket}/bob-training.jsonl"
    
    UploadBobPromptCommand:
      Description: PowerShell command to upload the training JSONL file
      Value: !Sub "aws s3 cp Bedrock/bob-prompt.txt s3://${BobTrainingBucket}/bob-prompt.txt"

    StartModelTrainingCommand:
      Description: PowerShell command to start the Bedrock model customization job
      Value: !Sub "aws bedrock start-model-customization-job --region ${AWS::Region} --job-name bob-training --custom-model-name bob-v1 --base-model-identifier mistral.mistral-7b-instruct-v0:2 --training-data-s3-uri s3://${BobTrainingBucket}/bob-training.jsonl --role-arn ${BedrockCustomizationRole.Arn}"
